# Default Variables
sentry_admin_email: "{{ ansible_env.SENTRY_ADMIN_EMAIL | default('admin@sentry.com') }}"
sentry_admin_password: "{{ ansible_env.SENTRY_ADMIN_PASSWORD | default('admin') }}"

sentry_repo_path: "/home/ubuntu/self-hosted"
sentry_repo_url: "https://github.com/getsentry/self-hosted.git"
sentry_repo_branch: "master"

sentry_docker_async_timeout: 600
sentry_docker_poll_interval: 10